apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: podplate
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: podplate-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: podplate-secrets
                  key: MONGO_PASSWORD
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - "--username"
                - "admin"
                - "--password"
                - "adminpassword"
                - "--authenticationDatabase"
                - "admin"
                - "--eval"
                - "db.runCommand({ ping: 1 }).ok"
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 20
          readinessProbe:
            exec:
              command:
                - mongosh
                - "--username"
                - "admin"
                - --quiet
                - "--password"
                - "adminpassword"
                - "--authenticationDatabase"
                - "admin"
                - "--eval"
                - "db.runCommand({ ping: 1 }).ok"
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: podplate
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
